### ISSUE TITLE
FileCache exists function always returns that cache does not exists.

### ISSUE THREAD

**Issue by Jeroen12345** [moust/silex-cache-service-provider#3]
In FileCache class, the exists function always returns false.

The fetch function, expects the cache key, but in the exists function, the filename is passed to the fetch function.

So

    public function exists($key)
    {
        return !!$this->fetch($this->getFileName($key));
    }

Should be changed to:

    public function exists($key)
    {
        return !!$this->fetch($key);
    }

**Comment by moust** [comment]
You're right. I just fix it quickly (82e4840).
Thanks.
