### ISSUE TITLE
Config error ? 

### ISSUE THREAD

**Issue by GreGosPhaTos** [moust/silex-cache-service-provider#4]
Hi, 

I followed the doc, so here is my bootstrap :
```php
$app['cache.options'] = array(
    'driver' => 'redis',
    'redis' => function() {
        $redis = new \Redis();
        $redis->connect('myserver', 6379);
        return $redis;
    }
);

``` 
Doesn't work...

And when I launch my debugger, at this line in RedisCache.php
```php
if (!isset($options['redis']) || !$options['redis'] instanceof Redis) {
    //default connection
}
```

The debugger goes inside the loop ... And it shouldn't go inside
Because the closure never called.

I think the code should be something like : 
```php
if (!isset($options['redis']) || !is_callable($options['redis']) || !$options['redis']() instanceof Redis) {
   //default connection
}
``` 
Same code for the other providers but i didn't try them.
What do you think ?

**Comment by moust** [comment]
I just tested it on my machine and the actual implementation works well.

I used the following initialization :
```php
$app->register(new CacheServiceProvider(), array(
    'cache.options' => array(
        'driver' => 'redis',
        'redis' => function () {
            $redis = new \Redis();
            $redis->connect('127.0.0.1');
            return $redis;
        }
    ),
));
```

**Comment by GreGosPhaTos** [comment]
Yes working because you have the same connection parameters than the default one ('127.0.0.1'). 
But try to put a var_dump or a die in your loop like : 

```php
if (!isset($options['redis']) || !$options['redis'] instanceof Redis) {
    die('Should not be there, this is the default config not mine');
}
```

**Comment by GreGosPhaTos** [comment]
OK fixed here : https://github.com/moust/silex-cache-service-provider/pull/5
