### ISSUE TITLE
1.0.x-dev dont work in Silex 1.3

### ISSUE THREAD

**Issue by JekaKey** [moust/silex-cache-service-provider#8]
Earlier everything worked, but now 1.0 also want pimple 3.0, while silex 1.3 use pimple 2.0.
How to fix this?

**Comment by moust** [comment]
I think it's due to a mistake in composer.json. I forgot to bump the version. I just publish a v1.0 and v2.0.1 releases to fix that.
Set `silex-cache-service-provider` dependency to `~1.0` should resolve your problem I think.

**Comment by JekaKey** [comment]
Yes! Everything is fine now!
Thank you!
